@startuml

component testedCBM
note right
    CBM in CWD
end note

package "@server-state/cli" as sersta {
component "cli"

[testEnvironment] <|- [cli]: < requires

component testEnvironment

[cli] --> webpack: > compiles
webpack --> HTTP: > serves
testEnvironment ..> webpack: > goes into
testedCBM ..> webpack: > goes into
}

testEnvironment -|>testedCBM: > dynamically reosolves

testedCBM -[hidden]> webpack
@enduml
