@startuml
skinparam componentStyle uml2

interface HTTP
node Server {
    component "simple-server" as ss
    component "server-base" as sb
    component "client-base" as cb

    [ss] -- [cb] : serves >
    ss -- sb
}

node "External Modules" {
    component "SM(s)" as sm1
    component "CBM(s)" as cbm
    [sb]--> [sm1]: > use
    [cb]->[cbm]: > use
}

node "Authentication Provider" {
    database DB
    component "JWT Implementation" as auth
    interface sqlite

    [auth] -- sqlite
    sqlite .> DB : use
}

HTTP -- [ss]
ss .> auth : use
@enduml
